trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  buildPlatform: 'x64'
  buildConfiguration: 'release'
  major: 1
  minor: 0
  revision: $[counter('rev', 0)]

steps: 
- task: GoTool@0
  inputs:
    version: '1.15.3'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/monit_exporter-$(major).$(minor).$(revision).linux-amd64
  displayName: build directory
- task: Go@0
  inputs:
    command: 'build'
    arguments: '-o $(Build.ArtifactStagingDirectory)/monit_exporter-$(major).$(minor).$(revision).linux-amd64/monit_exporter'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- script: |
    tar  --remove-files -C $(Build.ArtifactStagingDirectory) -zcf $(Build.ArtifactStagingDirectory)/monit_exporter-$(major).$(minor).$(revision).linux-amd64.tar.gz --format=posix  --owner=nobody --group nobody monit_exporter-$(major).$(minor).$(revision).linux-amd64
  displayName: package
- task: GithubRelease@0
  displayName: 'Create GitHub Release'   
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    tagSource: manual
    tag: v$(major).$(minor).$(revision)
    gitHubConnection: github.com_freedge
    repositoryName: freedge/monit_exporter
    assets: |
      $(Build.ArtifactStagingDirectory)/*.tar.gz
